# Generated by Django 5.0.4 on 2024-05-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookingApp", "0003_booking_payment_status"),
        ("paymentApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment_service",
            name="service",
        ),
        migrations.AddField(
            model_name="payment_service",
            name="booking",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookingApp.booking",
            ),
            preserve_default=False,
        ),
    ]
