# Generated by Django 5.0.4 on 2024-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookingApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="date",
            new_name="booking_date",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
