# Generated by Django 5.0.4 on 2024-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookingApp", "0002_rename_date_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
