# Generated by Django 5.0.4 on 2024-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="HOD",
            field=models.BooleanField(default=False),
        ),
    ]
