# Generated by Django 5.0.4 on 2024-04-29 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("serviceApp", "0002_service_sevice_image_subservice_subsevice_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="sevice_image",
            new_name="service_image",
        ),
    ]
