# Generated by Django 5.0.4 on 2024-05-07 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("serviceApp", "0003_rename_sevice_image_service_service_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subservice",
            old_name="subSevice_image",
            new_name="subService_image",
        ),
        migrations.RemoveField(
            model_name="subservice",
            name="HOD",
        ),
    ]
